### ISSUE TITLE
The latest cwltool does not create folder `/var/spool/cwl` as default anymore

### ISSUE THREAD

**Issue by lindaxiang** [ICGC-TCGA-PanCancer/Seqware-BWA-Workflow#20]
We tested with the latest version of cwltool, it does not create folder `/var/spool/cwl` as default anymore.
This will break the codes in `start.sh`:
https://github.com/ICGC-TCGA-PanCancer/Seqware-BWA-Workflow/blob/develop/scripts/start.sh#L8

**Comment by lindaxiang** [comment]
cwltool 1.0.20180116213856  works fine.

**Comment by garyluu** [comment]
This is probably fixed now.

**Comment by junjun-zhang** [comment]
fixed in #22
